[profile.release]
opt-level = "z"
lto = true
codegen-units = 1

[package]
authors = ["stefa-n"]
name = "twitch-drops-bot"
version = "0.1.2"
edition = "2021"

[dependencies]
ctrlc = "3.4.1"
thirtyfour = "0.31.0"
tokio = "1.32.0"
