[package]
authors = ["stefa-n"]
name = "twitch-drops-bot"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.1"
thirtyfour = "0.31.0"
tokio = "1.32.0"
